### ISSUE TITLE
Request for "Stop Scan" capability

### ISSUE THREAD

**Issue by ryan-sheldrake** [openclarity/vmclarity#281] opened 2023-04-26 09:28 UTC
## Problem Statement

If a user accidentially exits the scan configuration step with say "all" this could start a large amount of scans. There does not seem a safety net and/or way to cancel these mistakenly triggered scans

## Proposed Solution

Add a "cancel/stop scan" button in the below screen that terminates the underlying instance performing the scan 
![clarityVM- stop scan](https://user-images.githubusercontent.com/20015808/234533338-9e0aac4a-d4c4-4580-99be-0eda2ef41092.jpg)

## Alternatives Considered

Perhaps don't auto initiate the scans on exit from configuration definition and have the user go to a screen to to say "Go" - this could also be a useful API endpoint if it doesn't already exist. 

## Additional Context

The ability to cancel could save end users real world cost and overhead

**Comment by sambetts-cisco** [comment] 2023-04-26 10:38
Hey @ryan-sheldrake thanks for taking a look at VMClarity!

We actually just merged the option to abort a scan, it was something we wanted before KubeCon but the implementation took longer than intended. It can be initialised from the API by PATCHing the running scan object with `"State": "ABORTED"` or by going to the "Scans" screen and clicking the little stop icon. The abort will cascade to the AssetScans.

We currently don't have the option to cancel/abort a specific AssetScan within a Scan, only the entire Scan itself. Does this cover your use case?

I personally have also been affected by clicking "Save" in the configuration and it automatically triggering scans, even though I hadn't intended it too. I think we need to work on the UX there. @galiail @akpsgit WDYT? There are couple of improvements I can envision: 
a) Perhaps we default scheduling to Disabled, and then have  "Save" + "Save and Enable Scheduling"?  That way people can work on a scan configuration multiple times without worrying that it'll start doing stuff before they are ready.
b) We need to make it more obvious that you've not visited part of the configuration wizard yet so that it prompt you to check the scheduling configuration.

**Comment by sambetts-cisco** [comment] 2023-04-26 13:02
> I pulled the latest stable release v0.3.0. I can't see the stop scheduled run/all scan button. I guess that's in the active dev branch, presently?

Right, its in the dev branch, here's the PR: https://github.com/openclarity/vmclarity/pull/218. It should not be long until we cut another release which includes the recent changes. Although not recommended the VMClarity.cfn from main can be installed to use the most recent dev build if you want to try it out.

**Comment by akpsgit** [comment] 2023-04-30 07:20
Hi @ryan-sheldrake, the "Stop scan" capability is now available in the latest release v0.4.0. The scan can be stopped from the Scans table or in a drill down of a specific scan. Thanks a lot!

@sambetts-cisco, if starting a scan immediately is not the the default required/expected behavior during config creation, we can definitely discuss the options.

**Closed by akpsgit** 2023-04-30 07:20 UTC
